### PR TITLE
Ignore publishing of config file if package is run under Lumen

### PR DESCRIPTION
**Pull request by andyundso**
Hello, thanks for the good package, was exactly what I was looking for one of my projects.

Because we run Lumen and not Laravel, the publishing of the config file is apparently not possible. Still, if I included the package, my application crashed because Lumen was unable to push the config file. So I basically added a check in the ServiceProvider if the package is run under Lumen and if yes, it won't do this publishing thing.

Hope you can have a look and merge it if everything is good. Best regards, Andy

### CODE REVIEW

**Comment by richan-fongdasen** [comment]
Hi @andyundso. I am glad to know that you found this package helpful. To be honest, i've never used this package in Lumen before. But i also have a plan to use this package in my future Lumen project.

So i am wondering, would the package work perfectly in Lumen, just by implementing the small changes in this pull request? In my humble opinion, it would be nice if we also have tests for Lumen. :cheers:

**Comment by andyundso** [comment]
Hi @richan-fongdasen, thanks for your feedback. I didn't notice anything else yet that didn't work, but our application is still in development  and so there is the chance that something could not work, but we did not hit it until now.

For the Lumen test, should I just add a test which checks if the code wasn't executed if the environment was set to Lumen, or should I extend the Travis config so each Lumen version from 5.2 up to 5.7 also runs the whole test suite? Regards, Andy

**Comment by andyundso** [comment]
Hi @richan-fongdasen, did you already have a look at my last comment?

**Comment by andyundso** [comment]
Hi @richan-fongdasen, did you already have a look at my messages?

**Comment by richan-fongdasen** [comment]
Hi @andyundso, i am so sorry for the very late late reply. I have been looking into this issue and i think there is no way for us to test the package in Lumen environment at this moment.

Please take a look at this for reference : https://github.com/orchestral/testbench/issues/99

The package is using https://github.com/orchestral/testbench to make the tests easier. So we can only add support for Lumen Application without any automated tests.

Have you tested this package in a Lumen application? I think i am going to accept the pull request if you say that this package works well in Lumen Application with the proposed changes.
:cheers:

**Comment by andyundso** [comment]
Hi @richan-fongdasen, thanks for the reply. 

We implemented my fork with Lumen fix over at https://github.com/stiftungswo/betterDime and it's working great so far. The code I added is mostly taken from https://github.com/barryvdh/laravel-dompdf/blob/master/src/ServiceProvider.php, which is a much larger project and the Lumen fix works for them since the last four years (https://github.com/barryvdh/laravel-dompdf/commit/f4bc77289c9c20307a6e2889414a7a3b8db79b8d).

Would be great if you notify me as soon as the PR got merged, so I can switch out my fork at our project for the stable version from your repository.

Have a great day, Andy

**Comment by richan-fongdasen** [comment]
Hi @andyundso. I just want to let you know that this pull request has been merged and the changes has been added to the new release. Please check it out.

Thanks

**Pull request merged**
