### PR TITLE
Support PHP 8

### PR DESCRIPTION
**Pull request by bakerkretzmar**
This PR updates `composer.json` to allow installation in apps running on PHP 8.

**Todo**

- [x] As far as I know Travis doesn't support PHP 8. I'm happy to take a stab at migrating your Travis CI setup to GitHub Actions if you're interested in doing that.
- [x] One of your dependencies, `ekino/phpstan-banned-code`, also doesn't support PHP 8 yet. Based on the small size of this package and the small amount of forbidden code you're using it for right now, would you consider removing it temporarily until they add support?

### CODE REVIEW

**Comment by richan-fongdasen** [comment]
Hi @bakerkretzmar 

I think it is a good idea to add support for PHP 8.0. You have stated the update steps clearly. Moreover, I don't mind migrating from Travis CI to Github Actions also I don't mind disabling the `ekino/phpstan-banned-code` package for a while.

I am looking forward to the pull request updates 😃 

By the way, thanks in advance for the contribution 🥂

**Comment by bakerkretzmar** [comment]
@richan-fongdasen sounds great, take a look! Not sure why the workflows aren't running in this PR, but you can see their output at bakerkretzmar/eloquent-blameable#1 (they all pass).

**Comment by richan-fongdasen** [comment]
@bakerkretzmar The Github Actions Workflow is not working in this repository because the source code changes have not merged yet. But I can see the workflow works as expected in your forked repository. So I am going to merge this pull request now.

Thanks for the help. I really appreciate it. 🍻

**Comment by bakerkretzmar** [comment]
@richan-fongdasen thanks a lot!

**Pull request merged**
